# Generated by Django 2.2.1 on 2019-06-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pumpkins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Atlanta', 'Atlanta'), ('Baltimore', 'Baltimore'), ('Boston', 'Boston'), ('Chicago', 'Chicago'), ('Columbia', 'Columbia'), ('Dallas', 'Dallas'), ('Detroit', 'Detroit'), ('Los_Angeles', 'Los_Angeles'), ('Miami', 'Miami'), ('New_York', 'New_York'), ('Philadelphia', 'Philadelphia'), ('San_Fransisco', 'San_Fransisco'), ('St_Louis', 'St_Louis')], default='Atlanta', max_length=100)),
                ('variety', models.CharField(choices=[('HOWDEN_TYPE', 'HOWDEN TYPE'), ('PIE_TYPE', 'PIE TYPE'), ('MINIATURE', 'MINIATURE'), ('HOWDEN_WHITE_TYPE', 'HOWDEN WHITE TYPE'), ('CINDERELLA', 'CINDERELLA'), ('FAIRY_TALE', 'FAIRY TALE'), ('BIG_MACK_TYPE', 'BIG MACK TYPE'), ('MIXED_HEIRLOOM_VARIETIES', 'MIXED HEIRLOOM VARIETIES'), ('BLUE_TYPE', 'BLUE TYPE'), ('KNUCKLE_HEAD', 'KNUCKLE HEAD')], default='HOWDEN_TYPE', max_length=100)),
                ('date', models.DateField()),
                ('low_price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('high_price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'ordering': ('city',),
            },
        ),
    ]
