# Generated by Django 2.2.1 on 2019-06-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkinPrices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pumpkins',
            new_name='Pumpkin',
        ),
    ]
