# Generated by Django 2.2.1 on 2019-06-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumpkinPrices', '0003_auto_20190607_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpkin',
            name='variety',
            field=models.CharField(choices=[('HOWDEN_TYPE', 'HOWDEN TYPE'), ('PIE_TYPE', 'PIE TYPE'), ('MINIATURE', 'MINIATURE'), ('HOWDEN_WHITE_TYPE', 'HOWDEN WHITE TYPE'), ('CINDERELLA', 'CINDERELLA'), ('FAIRY_TALE', 'FAIRY TALE'), ('BIG_MACK_TYPE', 'BIG MACK TYPE'), ('MIXED_HEIRLOOM_VARIETIES', 'MIXED HEIRLOOM VARIETIES'), ('BLUE_TYPE', 'BLUE TYPE'), ('KNUCKLE_HEAD', 'KNUCKLE HEAD')], default='HOWDEN_TYPE', max_length=100),
        ),
    ]
